### PR TITLE
`numobs` and `getobs` support for Tables.jl's tables

### LINKED ISSUE #61: Can MLUtils play nicely with Tables.jl?
I think one could get greatly increase buy-in for MLUtil.jl if every Tables.jl compatible table would automatically implement the "data container" API. To get performance, one would still want to implement the concrete table types as well, but having it "just work" for all tables would be nice.  I guess, since "table" is itself just an interface, rather than an abstract type, this would need to be implemented as part of the data container API, right? As Tables.jl is very lightweight, I don't see that as a big issue (and I could probably find someone to help with the integration).   

Even so, there seems to be a problem implementing the interface for certain tables.  MLUtils.jl interprets tuples in a very specific way. For example `shuffleobs((x1, x2))` treats `x1` and `x2` as separate data containers, which are to be shuffled simultaneously, with the *same* base observation index shuffle.  **But some tables are tuples.** The following example is even a tuple-table whose elements are themselves tables (of a different type):

```julia
julia> X
((a = [1, 3], b = [2, 3]), (a = [2, 5], b = [4, 7]))

julia> Tables.istable(X)
true
```
So is such a tuple a pair of data containers or a single data container? The current API cannot distinguish them.

I wonder:

1.  How attached are people to current tuple-based dispatch for coupled multi-container processing?
2. Is there a big use-case for tables that are also tuples? @quinnj

Possibly [this discussion](https://github.com/JuliaML/MLDataUtils.jl/issues/46) is related. 

Tables that are tuples are problematic [elsewhere](https://github.com/JuliaAI/ScientificTypes.jl/issues/182). 

@oxinabox @rikhuijzer @darsnack

### PR DESCRIPTION
**Pull request by CarloLucibello**
Thanks to the recent introduction of the `subset` api in Tables.jl we can now support generic tables.

Close #61, close #87

### CODE REVIEW

**Comment by darsnack** [comment]
Dispatching on `istable` is going to cause type inference issues. Maybe implement it as a separate dispatch using a traits package like suggested [here](https://github.com/JuliaML/MLUtils.jl/issues/61#issuecomment-1049388014)

**Comment by CarloLucibello** [comment]
> Dispatching on istable is going to cause type inference issues. Maybe implement it as a separate dispatch using a traits package like suggested https://github.com/JuliaML/MLUtils.jl/issues/61#issuecomment-1049388014.

done, seems to work well

**Comment by ablaom** [comment]
I'll take a look at this soon.

**Review by ablaom — APPROVED** [review]
This looks good to me. I just wonder about the choice `viewhint=false`. Is this because `MLUtils` generally tries (requires?) copies to be made by `getobs`? In my own use-cases I am inclining towards avoiding the copy when that is possible (so `viewhint=true`). 

It might be nice to allow passing the `viewhint` option through to `getobs`, but perhaps that rubs against the current interface, and in any case could be added later?

Finally, perhaps we should check if there are likely overheads from the trait dispatch, as previously flagged. I see that SimpleTraits.jl has the utility [`@check_fast_traitdispach`]. Perhaps that helps settle the issue.

**Comment by ablaom** [comment]
One final note regarding documentation. I have been chastised for equating "istable(X) = true" with "satisfies the Tables.jl interface". The implication goes only in the  "=>" direction: you can have `istable(X) = false` for tables that implement the interface. So, that distinction should be made clear in any docs.

**Comment by CarloLucibello** [comment]
> This looks good to me. I just wonder about the choice viewhint=false. Is this because MLUtils generally tries (requires?) copies to be made by getobs? In my own use-cases I am inclining towards avoiding the copy when that is possible (so viewhint=true).

`getobs` by design always materializes and never returns a view, we have `obsview` for that.

**Comment by CarloLucibello** [comment]
> Finally, perhaps we should check if there are likely overheads from the trait dispatch, as previously flagged. I see that SimpleTraits.jl has the utility [@check_fast_traitdispach](https://github.com/mauro3/SimpleTraits.jl#performance). Perhaps that helps settle the issue.

dispatch is fast:
```julia
julia> using MLUtils, SimpleTraits, Test

julia> x = (a=rand(3), b=rand(3));

julia> @check_fast_traitdispatch MLUtils.IsTable typeof(x) true
true
```

**Comment by ablaom** [comment]
@CarloLucibello Thanks for those explanations and your work here.

**Pull request merged**
