### PR TITLE
numobs and  getobs

### PR DESCRIPTION
**Pull request by CarloLucibello**
Porting `nobs`, `getobs` and `getobs!` from https://github.com/JuliaML/LearnBase.jl/pull/53 with the following differences
- `nobs` is renamed to `numobs`, to avoid conflicts with `StatsBase.nobs`
- We get rid of the `obsdim` keyword, which causes a lot of additional complexity in the implementation here and in downstream packages. Wrapper types can be used in place of it.

### CODE REVIEW

**Comment by darsnack** [comment]
What would the wrapper type alternatives to the keyword look like?

**Comment by CarloLucibello** [comment]
something like this for `obsdim=1`
```
struct MyDataset
  A::AbstractArray
end
getobs(d::MyDataset, i) = d[i, :]
```
We can also provide a `ArrayDataset{D}`  where `D` parameterizes the observation dimension. I think it is better to have the type set the observation dim than having to deal with the `obsdim` keyword during the whole downstream pipeline

**Comment by CarloLucibello** [comment]
Merging as I would like to go on with the port

**Comment by ToucheSir** [comment]
If/when https://github.com/JuliaLang/julia/pull/32310 lands, that could be used over a custom dataset type.

**Pull request merged**
