### PR TITLE
port DataLoader from Flux

### LINKED ISSUE #13: add multitaksing to DataLoader
Port the DataLoader from Flux and extend it with the multitasking features of 
https://github.com/lorenzoh/DataLoaders.jl

### PR DESCRIPTION
**Pull request by CarloLucibello**
Fix #13

### CODE REVIEW

**Comment by darsnack** [comment]
Doesn't this just overlap with DataLoaders.jl? That's already LearnBase.jl compatible and more full-featured. Seems like we'd rather port that over.

**Comment by CarloLucibello** [comment]
I'm not familiar with DataLoaders.jl yet, so I'm porting Flux's one and the corresponding tests first so that we pinpoint a non-breaking replacement for Flux. I will port DataLoaders.jl in a second PR.

**Comment by CarloLucibello** [comment]
We want to port DataLoaders.jl here and not just reexport, right?

**Comment by darsnack** [comment]
> We want to port DataLoaders.jl here and not just reexport, right?

Yeah that's right. And your plan sounds good just want to check in that the long term `DataLoader` will end up matching DataLoaders.jl.

**Pull request merged**
